version: "3"

services:
 
    web:
        build: .
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - ./monitoring_tests:/usr/web/app
        ports:
            - "8000:8000"
        depends_on:
            - influxdb
        links:
            - influxdb
            
    influxdb:
        image: influxdb:latest
        ports:
            - "8086:8086"
        volumes:
            - influxdb-storage:/var/lib/influxdb
        environment:
            - DOCKER_INFLUXDB_INIT_MODE=setup
            - DOCKER_INFLUXDB_INIT_USERNAME=admin
            - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
            - DOCKER_INFLUXDB_INIT_ORG=my-org
            - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
    